package org.exoplatform.selenium.cloud.features;

import static org.exoplatform.selenium.TestLogger.info;

import org.exoplatform.selenium.cloud.CloudBase;
import org.exoplatform.selenium.platform.ManageAccount;
import org.exoplatform.selenium.platform.NavigationToolbar;
import org.exoplatform.selenium.platform.UserGroupManagement;
import org.openqa.selenium.Keys;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * @author phuongdt
 *
 */
public class Cloud_Features_FirstLoginWizard extends CloudBase{
	ManageAccount magAccount;
	NavigationToolbar navBar;
	UserGroupManagement userGroup;

	@BeforeMethod
	public void beforeMethods() {
		initSeleniumTest();
		driver.get(baseUrl);
		driver.manage().window().maximize();
		magAccount = new ManageAccount(driver);
		navBar = new NavigationToolbar(driver);
		userGroup = new UserGroupManagement(driver);
		magAccount.signIn("root", "12345");
	}

	@AfterMethod
	public void afterMethods() {
		driver.quit();
	}

	/**
	 * Case ID:94245.
	 * Test Case Name: After a second Sign up , user should be connected to Intranet.
	 * Pre-Condition: The User is already signed in in the Intranet
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 * Note: Need to update qmetry, there is not any email notification
	 */
	@Test
	public  void test01_AfterASecondSignUpUserShouldBeConnectedToIntranet() {
		info("Test 1: After a second Sign up , user should be connected to Intranet");
		/*Step 1: 
		 * Input Data: 
		 *	- Open the Cloud Workspace platform
		 *	- Input an email of a user already member in the Intranet
		 *Expected Outcome: 
		 *	- An email is received with a valid link
		 */
		/*Step 2: 
		 *Input Data: 
		 *	- Click on the link
		 *Expected Outcome: 
		 *	- The authentification page is displayed
		 */
		/*Step 3:
		 *Input Data: 
		 *	- Input valid credentiels of the user
		 *Expected Outcome: 
		 *	- The user is connected to the Intranet Homepage
		 */
		initCloudUrl(0);
		driver.get(baseCloudUrl);
		enterEmail2Signup(GMAIL_ADDRESS);
		waitForAndGetElement(ELEMENT_REFRESH);

	}

	/**
	 * Case ID:94246 - Step1 should be displayed in the Wizard.
	 * Case ID:94247 - Step2 should be displayed in the Wizard
	 * Case ID:94251 - User should be able to select a default space.
	 * Case ID:94252 - Step3 should be displayed in the Wizard.
	 * Case ID:94253 - The label "Add email Address" should be removed
	 * Case ID:94254 - User should be able to add an email address.
	 * Case ID:94255 - User should be able to remove an email address.
	 * Case ID:94256 - The label of button "Finish"should be replaced by "Send".
	 * Case ID:94257 - User should be able to connect from the button "Send".
	 * Case ID:94262 - After Sign in a Wizard should be displayed.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 */
	@Test
	public  void test02_StepsShouldBeDisplayedInTheWizard() {
		info("Test 2: Steps should be displayed in the Wizard");
		Actions actions = new Actions(driver);
		String email1 = "john@acme.com";
		String email2 = "mary@acme.com";
		String username = getRandomString();
		String password = username;
		String firstName = username;
		String lastName = username;
		String displayName = username + " " + username;
		String email = username+"@gmail.com";
		
		/*Create data to test*/
		navBar.goToNewStaff();
		magAccount.addNewUserAccount(username, password, password, firstName, lastName, displayName, email, null, null, false);
		magAccount.signOut();
		type(ELEMENT_INPUT_USERNAME, username, true);
		type(ELEMENT_INPUT_PASSWORD, password, true);
		click(ELEMENT_SIGN_IN_BUTTON);
		
		/*Step 1 (Case ID:94246, 94262)
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps" - 94262
			- The First Step 1 is displayed "Complete your profile" with following fields
		 * 	- The First and Last name" fields display input value in the registration step
		 * 	- You current position field is empty
		 * 	- Add profile picture box 
		 *	- The button "Next" is displayed
		 *	- A Tip text is displayed: "Find and connect with your colleagues to see their latest updates in your activity stream.'
		 *	- A link "Skip to homepage" is displayed
		 */ 
		info("Verify step 1 welcome screen - Case ID:94246, 94262");
		waitForAndGetElement(ELEMENT_START_STEP_WIZARD).getText().contains("Welcome to eXo - Get started in 3 easy steps<");
		waitForAndGetElement(ELEMENT_COMPLETE_YOUR_PROFILE_STEP1_LABEL);
		waitForAndGetElement(ELEMENT_FIRST_LAST_NAME_TEXT);
		assert waitForAndGetElement(ELEMENT_FIRST_NAME_STEP1).getAttribute("value").equals(firstName);
		assert waitForAndGetElement(ELEMENT_LAST_NAME_STEP1).getAttribute("value").equals(lastName);
		waitForAndGetElement(ELEMENT_POSITION_STEP1_TEXT);
		assert waitForAndGetElement(ELEMENT_POSITION_STEP1).getAttribute("value").equals("");
		waitForAndGetElement(ELEMENT_PROFILE_PICTURE);
		waitForAndGetElement(ELEMENT_PROFILE_PICTURE_TEXT);
		waitForAndGetElement(ELEMENT_BUTTON_NEXT_FIRST_PAGE);

		assert (waitForAndGetElement(ELEMENT_TIP_STEP1).getText().
				contains("Find and connect with your colleagues to see their latest updates in your activity stream."));
		waitForAndGetElement(ELEMENT_TIP_TITLE_STEP1);
		waitForAndGetElement(ELEMENT_SKIP_STEP1);
		
		/*Step 2 (Case ID:94247)
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome: 
		 *	- The Second Step 2 is displayed "Join Spaces"
		 *	- A box of default spaces is displayed: "Create your own collaboration spaces for teams or specific projects. We've set up your first space to help you get started"
		 *	- The Default Space "Getting Started" and all valid spaces already created on Intranet are  displayed with checkbox
		 *	- The button "Next is displayed
		 *	- A tip text is displayed: Spaces provide the tools to make your internal work more productive, including wikis, forums, team calendars and more."
		 *	- A link "Skip to homepage is displayed
		 */
		info("Verify step 2 welcome screen - Case ID:94247");
		String defaultSpace = "Getting Started";
		click(ELEMENT_BUTTON_NEXT_FIRST_PAGE);
		waitForAndGetElement(ELEMENT_JOIN_SPACE_STEP2_LABEL);
		assert(waitForAndGetElement(ELEMENT_BOX_DEFAULT_SPACE_STEP2).getText().
				contains("Create your own collaboration spaces for teams or specific projects. We've set up your first space to help you get started."));
		waitForAndGetElement(ELEMENT_BUTTON_NEXT_SECOND_PAGE);
		waitForAndGetElement(ELEMENT_SPACE_CHECKBOX.replace("${spaceName}", defaultSpace),1,2);
		assert (waitForAndGetElement(ELEMENT_TIP_STEP2).getText().
				contains("Space provide the tools to make your internal work more productive, including wikis, forum, group calendars and more."));
		waitForAndGetElement(ELEMENT_SKIP_STEP2);
		
		/*Input Data: 
		 *	- Check Space from the list
		 *Expected Outcome:
		 *	- The checkbox is crossed
		 *	- The label of the button "Next" is replaced by "Join x space", where x is the number of checked spaces
		 */ 
		info("User should be able to select a default space. - Case ID:94251");
		check(ELEMENT_SPACE_CHECKBOX.replace("${spaceName}", defaultSpace),2);
		waitForAndGetElement(ELEMENT_JOIN_SPACE_BUTTON.replace("${number}", "1"));
		uncheck(ELEMENT_SPACE_CHECKBOX.replace("${spaceName}", defaultSpace),2);
		
		/*Step 3 (Case ID:94252)
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome: 
		 *	- The third Step 3 is displayed: Invite Coworkers"
		 *	- Intruction text is displayed: Send email invitations to your coworkers to connect with them in your social intranet
		 *	- A note text is displayed: (note : only people with the same email @domain will be invited to your social intranet. Other addresses with receive an invitation to discover eXo)
		 *	- A field to invite user to join Intranet is displayed with label "Add email address"
		 *	- The button "Finish" is displayed
		 *	- Tip text is displayed: Easly access your documents on your iPhone, iPad or Android device with the eXo mobile app."
		 */
		info("Verify step 3 welcome screen - Case ID:94252");
		click(ELEMENT_BUTTON_NEXT_SECOND_PAGE);
		waitForAndGetElement(ELEMENT_JOIN_SPACE_STEP3_LABEL);
		assert(waitForAndGetElement(ELEMENT_BOX_DEFAULT_SPACE_STEP3).getText().
				contains("Send email invitations to your coworkers to connect with them in your social intranet."));
		assert(waitForAndGetElement(ELEMENT_BOX_DEFAULT_SPACE_STEP3).getText().
				contains("(note: Only people with the same email @domain name will be invited to your social intranet. Other addresses will receive an invitation to discover eXo)"));
		waitForAndGetElement(ELEMENT_INPUT_EMAIL_ADDRESS);
		assert (waitForAndGetElement(ELEMENT_TIP_STEP3).getText().
				contains("Easily access your documents on your iPhone, iPad or Android device with the eXo mobile app"));;
		waitForAndGetElement(ELEMENT_BUTTON_FINISH_THIRD_PAGE);
		waitForAndGetElement(ELEMENT_SKIP_STEP3);
		
		info("The label Add email Address should be removed. - Case ID:94253");
		/*
		 *Input Data: 
		 *	- Focus the mouse on the field
		 *Expected Outcome: 
		 *	- The label "Add an email Address" is removed
		 */
		click(ELEMENT_INPUT_EMAIL_ADDRESS);
		
		info("User should be able to add an email address. - Case ID:94254");
		/*
		 *Input Data: 
		 *	- Input a valid email address in the field
		 *	- From the Keyboard, Press Enter
		 *Expected Outcome: 
		 *	- The email is displayed on a dismiss label
		 */
		type(ELEMENT_INPUT_EMAIL_ADDRESS,email1,false);
		actions.sendKeys(Keys.RETURN).build().perform();
		waitForAndGetElement(ELEMENT_EMAIL_REMOVE.replace("${name}", email1.substring(0,email1.indexOf("@"))));
		
		type(ELEMENT_INPUT_EMAIL_ADDRESS,email2,false);
		actions.sendKeys(Keys.RETURN).build().perform();
		waitForAndGetElement(ELEMENT_EMAIL_REMOVE.replace("${name}", email2.substring(0,email2.indexOf("@"))));
		
		info("The label of button Finish should be replaced by Send. - Case ID:94256");
		/*
		 *Input Data: 
		 *	- Input a valid email address in the field
		 *	- From the Keyboard, Press Enter
		 *Expected Outcome: 
		 *	- The label of the button "Finish" is replaced by "Send (x)" where (x) is the number of email
		 */
		waitForAndGetElement(ELEMENT_SEND_INVITE_BUTTON.replace("${number}","2"));
		
		info("User should be able to remove an email address. - Case ID:94255");
		/*
		 *Input Data: 
		 *	- Click on the cross from the dismiss label
		 *Expected Outcome: 
		 *	- The email is removed from the field
		 */
		click(ELEMENT_EMAIL_REMOVE.replace("${name}", email1.substring(0,email1.indexOf("@")-1)));
		waitForElementNotPresent(ELEMENT_EMAIL_REMOVE.replace("${name}", email1.substring(0,email1.indexOf("@"))));
		waitForAndGetElement(ELEMENT_SEND_INVITE_BUTTON.replace("${number}","1"));
		
		info("User should be able to connect from the button Send. - Case ID:94257");
		/*
		 *Input Data: 
		 *	- Click on the button "Send"
		 *Expected Outcome: 
		 *	- The user is connected to the Intranet Homepage
		 */
		click(ELEMENT_SEND_INVITE_BUTTON.replace("${number}","1"));
		waitForAndGetElement(ELEMENT_HOME_PAGE);
	}
	
	/**
	 * Case ID:94258.
	 * Test Case Name: User should be able to connect from the button "Finish".
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 */
	@Test
	public  void test03_UserShouldBeAbleToConnectFromTheButtonFinish() {
		info("Test 03 User should be able to connect from the button Finish");
		String username = getRandomString();
		String password = username;
		String firstName = username;
		String lastName = username;
		String displayName = username + " " + username;
		String email = username+"@gmail.com";
		
		/*Create data to test*/
		navBar.goToNewStaff();
		magAccount.addNewUserAccount(username, password, password, firstName, lastName, displayName, email, null, null, false);
		magAccount.signOut();
		
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your Profile"
		 *	- The button "Next" is displayed
		 **/
		type(ELEMENT_INPUT_USERNAME, username, true);
		type(ELEMENT_INPUT_PASSWORD, password, true);
		click(ELEMENT_SIGN_IN_BUTTON);
		
		/*
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome:
		 *	- The Second Step 2 is displayed "Join Spaces"
		 *	- The button "Next" is displayed 
		 */
		click(ELEMENT_BUTTON_NEXT_FIRST_PAGE);

		/*
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome: 
		 *	- The third Step 3 is displayed: Invite Coworkers"
		 *	- The field to invite user is displayed
		 *	- The button "Finish" is displayed
		 */
		click(ELEMENT_BUTTON_NEXT_SECOND_PAGE);
		
		/*
		 *Input Data: 
		 *	- Click on the button "Finish"
		 *Expected Outcome: 
		 *	- The user is connected to the Intranet Homepage
		 */ 
		click(ELEMENT_BUTTON_FINISH_THIRD_PAGE);
		waitForAndGetElement(ELEMENT_HOME_PAGE);

	}

	/**
	 * Case ID:94259.
	 * Test Case Name: User should be able to connect from the Step 1.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 */
	@Test
	public  void test04_UserShouldBeAbleToConnectFromTheStep1() {
		info("Test 04 User should be able to connect from the Step 1");
		String username = getRandomString();
		String password = username;
		String firstName = username;
		String lastName = username;
		String displayName = username + " " + username;
		String email = username+"@gmail.com";
		
		/*Create data to test*/
		navBar.goToNewStaff();
		magAccount.addNewUserAccount(username, password, password, firstName, lastName, displayName, email, null, null, false);
		magAccount.signOut();
		
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your Profile"
		 *	- The button "Next" is displayed
		 **/
		type(ELEMENT_INPUT_USERNAME, username, true);
		type(ELEMENT_INPUT_PASSWORD, password, true);
		click(ELEMENT_SIGN_IN_BUTTON);

		/*
		 *Input Data: 
		 *	- Click on the link "Skip to Homepage" is displayed
		 *Expected Outcome: 
		 *	- The user is connected to the Intranet Homepage
		 **/ 
		click(ELEMENT_SKIP_STEP1);
		waitForAndGetElement(ELEMENT_HOME_PAGE);

	}

	/**
	 * Case ID:94260.
	 * Test Case Name: User should be able to connect from the Step 2.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 */
	@Test
	public  void test05_UserShouldBeAbleToConnectFromTheStep2() {
		info("Test 05 User should be able to connect from the Step 2");
		String username = getRandomString();
		String password = username;
		String firstName = username;
		String lastName = username;
		String displayName = username + " " + username;
		String email = username+"@gmail.com";
		
		/*Create data to test*/
		navBar.goToNewStaff();
		magAccount.addNewUserAccount(username, password, password, firstName, lastName, displayName, email, null, null, false);
		magAccount.signOut();
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your Profile"
		 *	- The button "Next" is displayed
		 **/
		type(ELEMENT_INPUT_USERNAME, username, true);
		type(ELEMENT_INPUT_PASSWORD, password, true);
		click(ELEMENT_SIGN_IN_BUTTON);
		
		/*
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome:
		 *	- The Second Step 2 is displayed "Join Spaces"
		 *	- The button "Next" is displayed 
		 */
		click(ELEMENT_BUTTON_NEXT_FIRST_PAGE);

		/*
		 *Input Data: 
		 *	- Click on the link "Skip to Homepage" is displayed
		 *Expected Outcome: 
		 *	- The user is connected to the Intranet Homepage
		 **/ 
		click(ELEMENT_SKIP_STEP2);
		waitForAndGetElement(ELEMENT_HOME_PAGE);

	}

	/**
	 * Case ID:94261.
	 * Test Case Name: User should be able to connect from the Step 3.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 */
	@Test
	public  void test06_UserShouldBeAbleToConnectFromTheStep3() {
		info("Test 06 User should be able to connect from the Step 3");
		String username = getRandomString();
		String password = username;
		String firstName = username;
		String lastName = username;
		String displayName = username + " " + username;
		String email = username+"@gmail.com";
		
		/*Create data to test*/
		navBar.goToNewStaff();
		magAccount.addNewUserAccount(username, password, password, firstName, lastName, displayName, email, null, null, false);
		magAccount.signOut();
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your Profile"
		 *	- The button "Next" is displayed
		 **/
		type(ELEMENT_INPUT_USERNAME, username, true);
		type(ELEMENT_INPUT_PASSWORD, password, true);
		click(ELEMENT_SIGN_IN_BUTTON);
		
		/*
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome:
		 *	- The Second Step 2 is displayed "Join Spaces"
		 *	- The button "Next" is displayed 
		 */
		click(ELEMENT_BUTTON_NEXT_FIRST_PAGE);

		/*
		 *Input Data: 
		 *	- Click on the button "Next"
		 *Expected Outcome: 
		 *	- The third Step 3 is displayed: Invite Coworkers"
		 *	- The field to invite user is displayed
		 *	- The button "Finish" is displayed
		 */
		click(ELEMENT_BUTTON_NEXT_SECOND_PAGE);

		/*
		 *Input Data: 
		 *	- Click on the link "Skip to Homepage" is displayed
		 *Expected Outcome: 
		 *	- The user is connected to the Intranet Homepage
		 **/ 
		click(ELEMENT_SKIP_STEP3);
		waitForAndGetElement(ELEMENT_HOME_PAGE);

	}
	
	/**
	 * Case ID:94253.
	 * Test Case Name: The label "Add email Address" should be removed.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 * PENDING: Can't locate of element label "Add email Address"
	 * Refer: https://jira.exoplatform.org/browse/FQA-1372
	 */
	@Test (groups="pending")
	public  void test09_TheLabelAddEmailAddressShouldBeRemoved() {
		info("Test 9: The label Add email Address should be removed");
		/*- Sign In Intranet
		 *Input Data: 
		 *Expected Outcome: */


		/*- Click on the button "Next"
		 *Input Data: 
		 *Expected Outcome: */


		/*- Click on the button "Next"
		 *Input Data: 
		 *Expected Outcome: */


		/*- Focus the mouse on the field
		 *Input Data: 
		 *Expected Outcome: */ 

	}
	
	/**
	 * Case ID:94248.
	 * Test Case Name: User should be able to upload a profile picture.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 * PENDING: Can't upload profile picture
	 * Refer: https://jira.exoplatform.org/browse/FQA-1583
	 */
	@Test (groups="pending")
	public  void test03_UserShouldBeAbleToUploadAProfilePicture() {
		info("Test 4: User should be able to upload a profile picture");
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your profile" 
		 *	- Add profile picture box is displayed
		 */


		/*
		 *Input Data: 
		 *	- Click on the button "Browse" and Select a picture from your desktop
		 *Expected Outcome: 
		 *	- The picture is added to the icon
		 */ 
	}

	/**
	 * Case ID:94249.
	 * Test Case Name: User should be able to drag and drop a profile picture.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 * PENDING because cannot drag and drop image from local machine to profile picture
	 * Refer: https://jira.exoplatform.org/browse/FQA-1245
	 */
	@Test (groups="pending")
	public  void test04_UserShouldBeAbleToDragAndDropAProfilePicture() {
		info("Test 5: User should be able to drag and drop a profile picture");
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your profile" 
		 *	- Add profile picture box is displayed
		 */


		/*
		 *Input Data: 
		 *	- Drag and drop a picture to the "Add a profile picture" box
		 *Expected Outcome: 
		 *	- The picture is added to the icon
		 */ 
	}

	/**
	 * Case ID:94250.
	 * Test Case Name: Loading icon should be displayed.
	 * Pre-Condition: The User sign in Intranet for a First time
	 * Post-Condition: 
	 * Done with OSs and browsers : 
	 * Generated by phuongdt at 2013/12/31 10:42:15
	 * PENDING: Can't upload profile picture
	 * Refer: https://jira.exoplatform.org/browse/FQA-1583
	 */
	@Test (groups="pending")
	public  void test05_LoadingIconShouldBeDisplayed() {
		info("Test 6: Loading icon should be displayed");
		/*
		 *Input Data: 
		 *	- Sign In Intranet
		 *Expected Outcome: 
		 *	- The Wizard is displayed "Welcome to eXo - Get started in 3 easy steps"
		 *	- The First Step 1 is displayed "Complete your profile" 
		 *	- Add profile picture box is displayed
		 */


		/*
		 *Input Data: 
		 *	- Click on the button "Browse" and Select a picture from your desktop
		 *Expected Outcome: 
		 *	- A Loading icon is displayed during upload
		 */ 
	}
}